// <auto-generated />
namespace ibby_cms.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Foreignkeyisrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Foreignkeyisrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201808070739071_Foreign key is required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
